import numpy as np
import pandas as pd

featureList = [
    "DataUsed_UL",
    "DataUsed_DL",
    "Speed_UL",
    "Speed_DL",
    "LegacyDevicesExist",
    "StationaryVsMobile",
    "WifiScores_top3Devices", 
    "PhyRate",
    "SignalStrength",
    "NumClientsConnected",
    "NumAccessPoints",
    "MeanClientsPerAP",
    "ChannelSwitches",
    "WifiAssociations",
    "SON_status",
    "SON_SteerSuccessStatus",
    "NumDevicePowerCycles",
    "KeyProcessCrashes",
    "Latency",
    "HomeWifiScore",
    "HighSteeringCount",
    "HomesWithWifiCongestion",
    "PercentageOfDataOn5G",
    "ClientBandwidthUsed",
    "AirtimeCongestion",
    "ChannelOfOperation",
    "SON_PerClientSteer",
    "ActivePhyRate",
    "SuddenDropOfConnection",
    "RebootPerformedViaCustomer",
    "StationName",
    "NumNeighborsOnSameChannel",
    "NumOverallNeighbors",
    "NumNeighborsOnAdjChannel",
    "NumIPChanges",
    "ExtendedBackhaulRange",
    "EthernetAndNot1Gig"
]